### ISSUE TITLE
Research Proposal - Empirical Strategy - Initial Regression Periods

### ISSUE THREAD

**Issue by torbatschow** [torbatschow/CSSR_Project#5]
@Corrod3 asked:
_Should we make the regression for one year, for the average of the whole period, or for each time-state pair?
Selecting one year has the advantage that the data will be purely cross-sectional and there are no time-effects.
If we make the regression on each time-state pair we have a much larger number of observations, but we might have time-effects which cause problems._

My suggestion:
I am thinking it might be cool to do it for all state/year pairs and to present the results (significance levels only) in a table directly next to each other so we can see whether it "kind of" works at one glance. What do you think?

**Comment by Corrod3** [comment]
Mmmh, not sure whether it will be visible in the significant levels since we are not using the most efficient estimator in the state-year pair case. 

Everything I read on the issue suggest not to make a simple multiple regression in panel data. An easy example with similarity to our case is this:
http://www.wiwi.uni-muenster.de/05/download/studium/empiricalmethods/ss15/chapter_6.pdf
It is also an issue in this (but without satisfactory answer):
http://stats.stackexchange.com/questions/50054/can-i-apply-multiple-regression-analysis-on-panel-data

**Comment by torbatschow** [comment]
So what would be your suggestion? Just run one or two/three regressions in different points in time as a test?

**Comment by Corrod3** [comment]
Yeah, lets just pick 2000, 2007 and 2014. 

Am 28. Oktober 2016 11:37:55 MESZ, schrieb Torben Klausa notifications@github.com:
So what would be your suggestion? Just run one or two/three regressions
in different points in time as a test?

##

**Comment by torbatschow** [comment]
Underway. :)
