### ISSUE TITLE
Assignment 2 - Ready to hand it in?

### ISSUE THREAD

**Issue by torbatschow** [torbatschow/CSSR_Project#6]
I've implemented the changes that we have agreed upon earlier. If you, @Corrod3 , are fine with the result, feel free to send the link to the repository to @christophergandrud .

**Comment by Corrod3** [comment]
There was still an open merge conflict which I resolved. At the moment there are two alternative introduction paragraphs. Which one do you prefer? 

Most of the changes I incorporated are about expressions / reader friendliness. However, I changed equation 5 and included unobservable variables instead of dummies. If we would write the dummies we would need to write in dummy + koefficient for each period: teta00 \* dYear2000 +  teta01 \* dYear2001 + ... or introduce vector notation. As we are not really interested in the estimated dummy coefficience I don't see the point off writing them. Moreover, they are introduced as a technical trick to estimate the model which is hinted at in the last sentence.

**Comment by torbatschow** [comment]
Agreed - and handed in.
